version: '2.2'
volumes:
    shared: {}

services:
    proxy:
        image: "joshragem/proxy:20180512"
        ports:
            - "8080:8080"
        init: true
    example:
        volumes:
            - shared:/shared
        image: "joshragem/example"
        environment:
            http_proxy: "http://proxy:8080"
            https_proxy: "http://proxy:8080"
        links:
            - proxy:proxy
        init: true
    logger:
        volumes:
            - shared:/shared
        image: "joshragem/logger:20180512"
        init: true

