FROM joshragem/base:20180915
RUN apt-get install -y tinyproxy dnsmasq
COPY proxy/dnsmasq.conf /etc/dnsmasq.conf
COPY proxy/localdns.sh /bin/proxydns.sh
COPY proxy/tinyproxy.conf /etc/tinyproxy/tinyproxy.conf
COPY proxy/monitrc /etc/monit/monitrc
COPY proxy/run.sh /bin/run.sh
RUN chmod +x /bin/proxydns.sh /bin/run.sh
RUN chmod 0700 /etc/monit/monitrc

EXPOSE 8080

