FROM joshragem/base:20180915
RUN apt-get install -y gnupg2 apt-transport-https

COPY logger/run.sh /bin/run.sh
COPY logger/rotatelogs.sh /bin/rotatelogs.sh
COPY logger/monitrc /etc/monit/monitrc
RUN chmod 0700 /etc/monit/monitrc
RUN chmod +x /bin/run.sh
RUN chmod +x /bin/rotatelogs.sh

